### ISSUE TITLE
Pico Pi W port.

### ISSUE THREAD

**Issue by lorelolorelo** [andreasbrett/feathers2ducky#1]
Hey Andreas, recently I find your repo for feathers2ducky and looks awesome,  it's in your roadmap do the same for pico pi w? :)  Sorry for open the issue maybe in the wrong place :D

**Comment by andreasbrett** [comment]
I currently don't own a Pico W (only non-W Picos) so development is not possible atm. I think @dbisu is currently testing Pico W compatibility in his pico ducky repo (https://github.com/dbisu/pico-ducky/tree/picow). Maybe that's a better place to check. I don't know if and when I will have a Pico W and since circuitpython is still only in alpha stage for Pico W, I'm not keen on alpha testing.
